// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "262b551e-2421-4f99-871c-cd35b8344722";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onWATERPUMPChange();

CloudTemperatureSensor tEMPERATURE;
int lIGHT;
int sOIL_MOISTURE;
CloudRelativeHumidity hUMIDITY;
bool wATER_PUMP;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(tEMPERATURE, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lIGHT, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sOIL_MOISTURE, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(hUMIDITY, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(wATER_PUMP, READWRITE, ON_CHANGE, onWATERPUMPChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
